export const AllTexts = {
  PleaseEnterValidPassword: 'Your password must have at least six characters that are a combination of letters, numbers and symbols (@, #, $, %). The password must also contain both uppercase and lowercase letters.',
  AbsenceRulesAlert: 'In order to produce the best results, we suggest you repeat the previous session before advancing.',
  AppNeedToAccessExternalStorage: 'App needs access to your external storage so you can download file.',
  SendLinkForPasswordRecovery: 'We will send a link to your registered\n email for password recovery.',
  ChooseNumberOfPhrases: 'Choose the number of phrases you want to\n practice in each session',
  InvitaionToJoinAudia: 'Did you receive an invitaion to join\n Audia with a redeem code.',
  UnsavedChangesAlert: 'You have unsaved changes. Do you want to save your changes?',
  PleasePutRedeemCodeInBoxBelow: 'Please put your redeem code in the box below',
  PlaylistNullSubTitle: 'During a set tap the icon below\n to add to playlist',
  TakeYourPhotoOrChooseFromLibrary: 'Take your photo or choose from library',
  ArchiveNullSubTitle: "You haven't added any sound bite(s) in Archive.",
  FirstNameAtLeastTwoCharacter: 'First name at least 2 characters long',
  LastNameAtLeastTwoCharacter: 'Last name at least 2 characters long',
  PleaseEnterValidEmailAddress: 'Please enter a valid email address',
  AccessVerbSessionTitle: 'You now have access to verb sessions!',
  WeRecommendConnectingToWifi: 'We recommend connecting to wifi',
  PleaseSelectFromListBelow: 'Please select from the list below',
  LearnLangauageNaturalWay: 'Learn language the natural way.',
  ChooseNativeSpeaker: 'Choose male or female native speaker',
  NotMatchConfirmPassword: 'Confirm password doesn\'t match',
  PleaseSendRedeemCodeHere: 'Please send redeem code here',
  SelectNaturalLanguage: 'Select your natural language',
  PleaseEnterEmailAddress: 'Please enter email address',
  EnterCurrentPassword: 'Please enter current password',
  EnterConfirmPassword: 'Please enter confirm password',
  SelectLanguageToLearn: 'Select a language to learn',
  AlreadyHaveAnAccount: 'Already have an account?',
  YouCurrentlyOffline: 'You are currently offline',
  SureLogout: 'Are you sure you want to logout?',
  EnterNewPassword: 'Please enter new password',
  ConnectWithFacebook: 'Connect with Facebook',
  SignInWithFacebook: 'Sign in with Facebook',
  HowAudiaDifferent: 'How is Audia different',
  ForgotYourPassword: 'Forgot your password',
  DontHaveAnAccount: "Don't have an account",
  PlaylistNullTitle: 'Save and review up to',
  SettingScreenActiveDevice: 'Active Device',
  WaitingForNextSet: 'Waiting for next set',
  SettingScreenAccountInfo: 'Account Info',
  LostRedeemCode: 'lost your redeem code?',
  ChooseFromLibrary: 'Choose from Library',
  PreviousSessions: 'Previous Sessions',
  PrivacyPolicyTitle: 'Privacy Policy',
  TakeFromGallery: 'Take From Gallery',
  CurrentPassword: 'Current Password',
  TermsConditionTitle: 'Terms of Use',
  ConfirmPassword: 'Confirm Password',
  ForgotPassword: 'Forgot Password',
  ItalianEdition: 'Italian Edition',
  InAppPurchase: 'in-app purchase',
  PrivacyPolicy: 'Privacy Policy',
  SwitchProfile: 'Switch Profile',
  ActiveAccount: 'Active Account',
  VerbSessions: 'Verb Sessions',
  NativeSwitch: 'Native Switch',
  NoConnection: 'No Connection',
  Complete: 'Session Complete',
  Downloading: 'Downloading',
  EnterEmail: 'enter email',
  FirstName: 'First Name',
  Recording: 'Recordings',
  LastName: 'Last Name',
  Password: 'Password',
  Playlist: 'Playlist',
  AddUser: 'Add User',
  Archive: 'Archive',
  English: 'English',
  UpNext: 'Up Next',
  SignIn: 'Sign in',
  Cancel: 'Cancel',
  Email: 'E-mail',
  Error: 'Error!',
  Retry: 'Retry',
  Login: 'Login',
  Users: 'Users',
  Oops: 'Oops!',
  Play: 'Play',
  Next: 'Next',
  Send: 'Send',
  And: 'and',
  Yes: 'Yes',
  No: 'No',
  Ok: 'OK',
  Male: 'Male',
  Save: 'Save',
  Alert: 'Alert',
  NoWay: 'No way',
  Submit: 'Submit',
  Female: 'Female',
  AppName: 'Audia',
  GotIt: 'Got it!',
  SignUp: 'Sign up',
  IAgree: 'I Agree',
  Version: 'Version',
  Waiting: 'Waiting',
  NextSet: 'Next Set',
  LogoutText: 'Logout',
  Settings: 'Settings',
  Continue: 'Continue',
  Loading: 'Loading...',
  UserType: 'User Type',
  SampleOne: 'Sample 1',
  SampleTwo: 'Sample 2',
  ButtonAccept: 'Accept',
  SyncOfflineText: 'Sync',
  Play1Time: 'Play 1 time',
  RedeemCode: 'Redeem Code',
  TakePhoto: 'Take a Photo',
  SelectUser: 'Select User',
  AddNewUser: 'Add New User',
  Play3Times: 'Play 3 times',
  Play5Times: 'Play 5 times',
  ButtonOverride: 'Override',
  ButtonContinue: 'Continue',
  PlayListTitle: 'Playlists',
  NewPassword: 'new password',
  RecordingTitle: 'Recording',
  SetReminder: ' Set Reminder',
  Play10Times: 'Play 10 times',
  LastActivity: 'Last activity',
  OpenSettings: 'Open Settings',
  CreateAccount: 'Create Account',
  CreatePlayList: 'Create Playlist',
  NativeLanguage: 'Native Language',
  ChangePassword: 'Change Password',
  ContinuousPlay: 'Continuous Play',
  SwitchLanguage: 'Switch language',
  NoVerbsFound: 'No verb(s) found.',
  LetsGetStarted: "Let's get started",
  SavePreferences: 'Save Preferences',
  PreviousSessions: 'Previous Sessions',
  NoSessionsFound: 'No session(s) found.',
  UnableToLogin: 'We are unable to login.',
  ConfirmPreferences: 'Confirm Preferences',
  TermsAndConditions: 'Terms and Conditions',
  NoRecordingsFound: 'No Recording(s) found.',
  TimeElapse18HRS: 'Oops... press to restart',
  PleaseEnterPassword: 'Please enter password',
  UnableToFetch: 'We are unable to fetch data.',
  MicroPhonePermission: 'Microphone Permission',
  SoundLoopsPerSession: 'Sound loops per session',
  ThePauseRulesSuggest: 'We suggest you start over',
  NoInternetConnectionText: 'No internet connection.',
  NativeSpeakerPreference: 'Native speaker preference',
  FailedToUploadOnAWS3: 'Failed to upload image to S3',
  ProfileSaveSuccess: 'Your profile saved successfully.',
  CanWeAccessYourSettings: 'Can we access your settings?',
  BySigningUpYouAgreeToOur: 'By signing up, you agree to our',
  SomthingWentWrong: 'Something went wrong, please try again',
  AppNeedToSaveAudioFile: 'We need access for save audio file',
  EnableToChangePassword: 'We are unable to change your password.',
  YouWillChargedAfterSignUp: 'You will be charged after signing-up',
  WriteExternalStoragePermission: 'WRITE EXTERNAL STORAGE PERMISSION',
  PoorInternetConnention: 'Poor internet connection, please try again',
  ExternalStoragePermissionDenied: 'External storage permission denied',
  CouldNotGetYourRequest: 'We could not get your request, please try again',
  SeemsYouNotConnectedInternet: 'Seems you are not connected to the internet.',
  ThePauseRulesRestartSet: 'Oops... you waited too long,  we will restart this set',
  NewPasswordMustBeDifferentFromCurrent: 'Current and new password must be different',
  AccessVerbSessionSubTitle: 'Remember to complete your verb session before moving forward.',
  changePreference: 'This preference will apply from next session. You want to change preference?',
  AppNeedToAccessMicroPhone: 'AudioExample needs access to your microphone so you can record audio.',
  RulesAlertViewHeadingText: "If you're in a noisy environment, we suggest you use headphones for optimal",
  RulesAlertViewDescription: "We recommend you become immersed in the audia experience for the best results.",
  PendingDataForSync: 'There are some pending progress to sync with server, Are you sure you want to logout?',
  PrivacyPolicySubTitle: 'Lorem ipsum dolor sit amet, an his duis regione adversarium, mei in assum ubique voluptatum. Ex per nominati quaestio.',
  TermsConditionSubTitle: 'Lorem ipsum dolor sit amet, an his duis regione adversarium, mei in assum ubique voluptatum. Ex per nominati quaestio.',
};

export const colors = {
  _FFFFFF: '#FFFFFF',
  _FF687E: '#FF687E',
  _526F99: '#526F99',
  _ededed: '#ededed',
  _012c6a: '#012c6a',
  _A9A9A9: '#A9A9A9',
  _496A9D: '#496A9D',
  _C1C1C1: '#C1C1C1',
  _8C8C8C: '#8C8C8C',
  _4299FF: '#4299FF',
  _516C94: '#516C94',
  _5C789F: '#5C789F',
  _C6C073: '#C6C073',
  _1A9E8A: '#1A9E8A',
  _113B76: '#113B76',
  _00BB71: '#00BB71',
  _8095B4: '#8095B4',
  _3190FF: '#3190FF',
  _191948: '#191948',
  _EFF6FF: '#EFF6FF',
  _000000: '#000000',
  _637DA3: '#637DA3',
  _0C0C0C: '#0C0C0C',
  _7F94B1: '#7F94B1',
  _5C6D88: '#5C6D88',
  _F6F6F6: '#F6F6F6',
  _F2F3F4: '#F2F3F4',
  _A6A6A6: '#A6A6A6',
  _383838: '#383838',
  _9A9A9A: '#9A9A9A',
  _284C80: '#284C80',
  _5B6C84: '#5B6C84',
  _5FD4A6: '#5FD4A6',
  _A5E6ED: '#A5E6ED',
  _19C0D1: '#19C0D1',
  _7E59B5: '#7E59B5',
  _4C13A0: '#4C13A0',
  _855FBD: '#855FBD',
  _9CE4C7: '#9CE4C7',
  _10A96C: '#10A96C',
  _DCDCDC: '#DCDCDC',
  _EFEFEF: '#EFEFEF',
  _C4C5C6: '#C4C5C6',
  _13BD71: '#13BD71',
  _4A90E2: '#4A90E2',
  _01BB72: '#01BB72',
  _FFED73: '#FFED73',
  _F9F9F9: '#F9F9F9',
  _E71D36: '#E71D36',
  _4A4A4A: '#4A4A4A',
  _0093FF: '#0093FF',
  _9B9B9B: '#9B9B9B',
  _BFC3C5: '#BFC3C5',
  _EF536A: '#EF536A',
  _677FA1: '#677FA1',
  _7B7B7B: '#7B7B7B',
  _a8a8a8: '#a8a8a8',
  _8d8d8d: '#8d8d8d',
  _E6E6E6: '#E6E6E6',
  _0CBE78: '#0CBE78',
  _BDBDBD: '#BDBDBD',
  _00586C: '#00586C',
  _4E6C97: '#4E6C97',


  colorLightGray: '#FFFFFF',
  colorWhite: '#FFFFFF',
  colorGrey: '#88b8ff',
  colorDoveGrey: '#666666',
  colorBlue: '#5DA5ED',
  colorBlack: '#000000',
  colorGreen: '#13BD71',
  colorLightBlue: '#3B8BFF',
  colorDodgerBlue: '#1071FF',
  colorSeashellGrey: '#F1F1F1',
  colorSolitude: '#eaecee',
  colorRollingStone: '#7B7D81',
  colorPerano: '#A3B9F0',
  colorShuttleGray: '#5C626A',
  colorCornflowerBlue: '#4d8de9',
  colorMalibu: '#62A2FF',
  colorPorcelain: '#F5F6F7',
  colorSilver: '#cccccc',
  colorSilverChalice: '#adadad',
  colorMauvelous: '#f4879e',
  colorMirage: '#161e29',
  colorLightDodgerBlue: '#287FFF',
  colorLightMalibu: '#81ACFF',
  colorCobalt: '#0947b7',
  colorGray: '#a2a5a9',
  colorDarkPink: '#E8284D'
};

export const tableName = {
  user: 'User',
  userCourseDownload: 'UserCourseDownload',
  userCourseProgress: 'UserCourseProgress',
  userRecording: 'UserRecording',
  userSessionPreference: 'UserSessionPreference'

}